input {
  beats {
    port => 5044
  }
}

filter {
  csv {
    separator => ","
    columns => ["host","time","method","url","response","bytes"]
  }

  date {
    match => ["time", "dd/MMM/yyyy:HH:mm:ss Z"]
    target => "@timestamp"
  }

  mutate {
    convert => {
      "response" => "integer"
      "bytes"    => "integer"
    }
  }

  geoip {
    source => "host"
    target => "geoip"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "apache-logs"
  }
}
